from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
CONFIG_DIR = PROJECT_ROOT / "config"
DEFAULT_DATABASE_PATH = PROJECT_ROOT / "database" / "applications.db"

CONFIG_FILES = {
    "profile": CONFIG_DIR / "profile.yaml",
    "documents": CONFIG_DIR / "documents.yaml",
    "settings": CONFIG_DIR / "settings.yaml",
    "form_answers": CONFIG_DIR / "form_answers.yaml",
}

REQUIRED_DIRECTORIES = (
    PROJECT_ROOT / "config",
    PROJECT_ROOT / "database",
    PROJECT_ROOT / "documents" / "cvs",
    PROJECT_ROOT / "documents" / "templates",
    PROJECT_ROOT / "generated" / "motivation_letters",
    PROJECT_ROOT / "generated" / "form_answers",
    PROJECT_ROOT / "exports" / "excel",
    PROJECT_ROOT / "logs",
    PROJECT_ROOT / "database" / "backups",
    PROJECT_ROOT / "database" / "recovery_exports",
    PROJECT_ROOT / "samples" / "sample_job_posts",
)

STATUS_VALUES = (
    "Saved",
    "To Apply",
    "Applied",
    "Follow-up Needed",
    "Interview",
    "Rejected",
    "Accepted",
    "Archived",
)

SOURCE_PLATFORM_VALUES = (
    "LinkedIn",
    "Company Website",
    "Workday",
    "Greenhouse",
    "Lever",
    "Welcome to the Jungle",
    "Indeed",
    "Email",
    "Referral",
    "Other",
)

APPLICATION_CHANNEL_VALUES = (
    "LinkedIn Easy Apply",
    "LinkedIn External Link",
    "Company Career Page",
    "ATS Platform",
    "Email",
    "Referral",
    "Manual",
    "Other",
)

CONTRACT_TYPE_VALUES = (
    "Permanent",
    "CDI",
    "Temporary",
    "CDD",
    "Internship",
    "Apprenticeship",
    "Graduate Program",
    "Freelance",
    "Consulting",
    "ESN",
    "Unknown",
)

CV_KEYS = ("marketing", "consulting", "data_analysis", "ai")

LIST_FIELDS = (
    "key_responsibilities",
    "required_skills",
    "preferred_qualifications",
    "cv_matched_keywords",
)

APPLICATION_COLUMNS = (
    "application_id",
    "date_created",
    "date_updated",
    "company_name",
    "company_size",
    "company_industry",
    "company_website",
    "company_linkedin",
    "career_page_url",
    "job_title",
    "job_domain",
    "seniority_level",
    "contract_type",
    "job_length",
    "salary",
    "location",
    "remote_policy",
    "relocation_required",
    "key_responsibilities",
    "required_skills",
    "preferred_qualifications",
    "detected_language",
    "raw_job_description",
    "source_platform",
    "application_channel",
    "job_url",
    "status",
    "date_applied",
    "follow_up_date",
    "contact_person",
    "contact_url",
    "notes",
    "recommended_cv",
    "selected_cv",
    "cv_confidence_score",
    "cv_recommendation_reason",
    "cv_matched_keywords",
    "motivation_letter_required",
    "motivation_letter_language",
    "motivation_letter_file",
    "form_answers_file",
    "google_sheet_row_id",
    "normalized_company_name",
    "canonical_job_url",
    "external_job_id",
    "job_description_hash",
    "deleted_at",
    "tombstone_reason",
    "record_version",
    "sync_status",
    "sync_pending",
    "sync_hash",
    "sync_last_attempt_at",
    "sync_last_success_at",
    "sync_last_error",
    "sync_last_source",
    "archived",
)

EXTRACTION_SCHEMA_KEYS = (
    "company_name",
    "company_size",
    "company_industry",
    "company_website",
    "company_linkedin",
    "career_page_url",
    "job_title",
    "job_domain",
    "seniority_level",
    "contract_type",
    "job_length",
    "salary",
    "location",
    "remote_policy",
    "relocation_required",
    "key_responsibilities",
    "required_skills",
    "preferred_qualifications",
    "detected_language",
    "source_platform",
    "application_channel",
    "job_url",
    "motivation_letter_required",
)

EXTRACTION_LIST_FIELDS = (
    "key_responsibilities",
    "required_skills",
    "preferred_qualifications",
)

GOOGLE_SHEETS_COLUMNS = (
    "Application ID",
    "Date Created",
    "Date Updated",
    "Company Name",
    "Company Size",
    "Company Industry",
    "Company Website",
    "Company LinkedIn",
    "Career Page URL",
    "Job Title",
    "Job Domain",
    "Seniority Level",
    "Contract Type",
    "Job Length",
    "Salary",
    "Location",
    "Remote Policy",
    "Relocation Required",
    "Key Responsibilities",
    "Required Skills",
    "Preferred Qualifications",
    "Detected Language",
    "Source Platform",
    "Application Channel",
    "Job URL",
    "Status",
    "Date Applied",
    "Follow-up Date",
    "Contact Person",
    "Contact URL",
    "Notes",
    "Recommended CV",
    "Selected CV",
    "CV Confidence Score",
    "CV Recommendation Reason",
    "CV Matched Keywords",
    "Motivation Letter Required",
    "Motivation Letter Language",
    "Motivation Letter File",
    "Form Answers File",
    "Google Sheet Row ID",
    "Record Version",
    "Last Synced At",
    "Last Sync Source",
    "Local Updated At",
    "Sync Hash",
    "Deleted At",
    "Tombstone Reason",
    "Archived",
)

GOOGLE_COLUMN_TO_FIELD = {
    "Application ID": "application_id",
    "Date Created": "date_created",
    "Date Updated": "date_updated",
    "Company Name": "company_name",
    "Company Size": "company_size",
    "Company Industry": "company_industry",
    "Company Website": "company_website",
    "Company LinkedIn": "company_linkedin",
    "Career Page URL": "career_page_url",
    "Job Title": "job_title",
    "Job Domain": "job_domain",
    "Seniority Level": "seniority_level",
    "Contract Type": "contract_type",
    "Job Length": "job_length",
    "Salary": "salary",
    "Location": "location",
    "Remote Policy": "remote_policy",
    "Relocation Required": "relocation_required",
    "Key Responsibilities": "key_responsibilities",
    "Required Skills": "required_skills",
    "Preferred Qualifications": "preferred_qualifications",
    "Detected Language": "detected_language",
    "Source Platform": "source_platform",
    "Application Channel": "application_channel",
    "Job URL": "job_url",
    "Status": "status",
    "Date Applied": "date_applied",
    "Follow-up Date": "follow_up_date",
    "Contact Person": "contact_person",
    "Contact URL": "contact_url",
    "Notes": "notes",
    "Recommended CV": "recommended_cv",
    "Selected CV": "selected_cv",
    "CV Confidence Score": "cv_confidence_score",
    "CV Recommendation Reason": "cv_recommendation_reason",
    "CV Matched Keywords": "cv_matched_keywords",
    "Motivation Letter Required": "motivation_letter_required",
    "Motivation Letter Language": "motivation_letter_language",
    "Motivation Letter File": "motivation_letter_file",
    "Form Answers File": "form_answers_file",
    "Google Sheet Row ID": "google_sheet_row_id",
    "Record Version": "record_version",
    "Last Synced At": "sync_last_success_at",
    "Last Sync Source": "sync_last_source",
    "Local Updated At": "date_updated",
    "Sync Hash": "sync_hash",
    "Deleted At": "deleted_at",
    "Tombstone Reason": "tombstone_reason",
    "Archived": "archived",
}
